language: node_js
node_js:
  - "14"
dist: trusty
sudo: required

branches:
  only:
    - main

install:
  - npm install

cache:
  directories:
    - "./node_modules"

script:
  - ng lint
  - ng build --prod --base-href https://albotw.github.io/TombeDuCamion_CWA/
