language: node_js
node_js:
  - "9"
dist: trusty
sudo: required

branches:
  only:
    - main

before_script:
  - npm install -g @angular/cli

scripts: -ng lint
  -ng build --prod --base-href https://albotw.github.io/TombeDuCamion_CWA/
